package utils

import "Gopher_Dungeon_Arena/src/config"

const (
	//Jogador
	JOGADOR_TAMANHO_MUNDO = 20
	JOGADOR_TAMANHO_MAPA  = JOGADOR_TAMANHO_MUNDO / config.PROPORCAO_MAPA

	//Bot
	BOT_TAMANHO_MUNDO = 10
	BOT_TAMANHO_MAPA  = BOT_TAMANHO_MUNDO / config.PROPORCAO_MAPA

	BOT_VELOCIDADE_RAPIDA = 6
	BOT_VELOCIDADE_NORMAL = 5
	BOT_VELOCIDADE_LENTA  = 3
	BOT_VELOCIDADE_MINIMA = 0
	BOT_VELOCIDADE_MAXIMA = 6

	BOT_CICLOS_REPETICAO = 10

	//Parede
	PAREDE_TAMANHO_MUNDO = 30
	PAREDE_TAMANHO_MAPA  = PAREDE_TAMANHO_MUNDO / config.PROPORCAO_MAPA

	PORTAL_ENTRADA_TAMANHO = 50
)

const (
	COMBATE_BOT_RIT = 10
	COMBATE_JOGADOR_RIT = 30
)
